
function info = ParseLine(tline)
% To parse each item of the given line

stIdx = [1, findstr(tline, ',') + 1];    % Start Indexes
edIdx = [stIdx(2:end)-2, length(tline)];  % End Indexes

% Each line MUST contain the following information, in this exact order.
info = struct('time',  tline(stIdx(1):edIdx(1)),...
              'ID1',   tline(stIdx(2):edIdx(2)),...
              'dist1', tline(stIdx(3):edIdx(3)),...
              'ID2',   tline(stIdx(4):edIdx(4)),...
              'dist2', tline(stIdx(5):edIdx(5)),...
              'ID3',   tline(stIdx(6):edIdx(6)),...
              'dist3', tline(stIdx(7):edIdx(7)),...
              'ID4',   tline(stIdx(8):edIdx(8)),...
              'dist4', tline(stIdx(9):edIdx(9)));
% disp(info);

end